#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/.dotfiles
############################

########## Variables

configDir=~/.dotfiles/config
olddir=~/.dotfiles_old             # old dotfiles backup directory
files_config="alacritty btop corectrl easyeffects fish flameshot foot Genymobile glava goverlay hypr kitty konsolerc ksnip MangoHud mpv nwg-displays qBittorrent QDirStat safeeyes solaar spicetify swappy swaylock swaync thefuck Thunar vlc wezterm"    # list of files/folders to symlink in .config

########## temp for another repo? TODO:
# copyq kdedefaults

# create dotfiles_old in homedir
echo -n "Creating $olddir for backup of any existing dotfiles in ~ ..."
mkdir -p $olddir
echo "done"

# change to the dotfiles directory
echo -n "Changing to the $configDir directory ..."
cd $configDir
echo "done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
for file in $files_config; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/.$file ~/dotfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $configDir/$file ~/.config/$file
done

# another symlinks
ln -s $configDir/starship.toml ~/.config/starship.toml
sudo ln -s $configDir/environment_hyprland /etc/environment
ln -s ~/MEGAsync/Pictures ~/Pictures
ln -s ~/MEGAsync/Documents ~/Documents
