#!/bin/bash

COLOR=$(hyprpicker)

echo "${COLOR}" | wl-copy -n && (convert -size 32x32 xc:$(wl-paste) /tmp/color.png && notify-send "Color Code:" "$(wl-paste)" -h "string:bgcolor:$(wl-paste)" --icon /tmp/color.png -u normal -t 4000)

# notify-send -e -u "low" "Color copied!" "$COLOR" # TODO:

# hyprpicker -a && (convert -size 32x32 xc:$(wl-paste) /tmp/color.png && notify-send "Color Code:" "$(wl-paste)" -h "string:bgcolor:$(wl-paste)" --icon /tmp/color.png -u critical -t 4000)