#!/bin/bash

# VARIABLES:
timeout=2  # how many seconds will pass until it's the end.
soundsDir="$HOME/.config/hypr/sounds"
end_time=$(($(date +%s) + $timeout))
# whatdateisit=$(date +%Y-%m-%d-%H-%M%S)

# GLOBAL FUNCTIONS
countdown() { # Displays a message
  h="99"    # lenght of the bar of the notification
  t="900"   # how many miliseconds the notification is shown
  icon="/usr/share/icons/BeautyLine/preferences/scalable/preferences-system-login.svg"
  i=$1

  while (( $i > 0 )); do
    play -v 0.1 "$soundsDir/remove.wav"
    (( h -= 29 )) || true
    notify-send --app-name exit -t $t -e -h int:value:$h \
    -u 'normal' \
    -i $icon \
    "$message ⌛ in $i's";
    sleep 1
    ((i--))
  done
  pkill wev
  exit
}

check() {
while [ "$(date +%s)" -lt $end_time ]; do
    wev | grep -q 'key: 9' && notify-send -e -t 999 -u normal "Escape key pressed!" && exit
done
}

closing() {
  hyprctl dispatch closewindow thunar
}

exiting() {
if [ "$(date +%s)" -ge $end_time ]; then
  "${cya[@]}"
  pkill exit    # this is here just to avoid multiple instances open of the script when I was testing it, useless otherwise.
fi
}

# LOCAL FUNCTIONS

# This helps debugging, useless otherwise.
test() {  
  cya=(notify-send '.☠️☠️☠️☠️☠️☠️' '️..later aligator!!..🐊🐊' -e -t 999 -u 'normal' -i 'x')
  message="POWERing-OFF..."
  countdown "$timeout" &
  check
  exiting
}

shutdown() {
  cya=(systemctl poweroff -i)
  message="POWERing-OFF..."
  countdown "$timeout" &
  check
  # closing # TODO:
  exiting
}

restart() {
  cya=(systemctl reboot)
  message="RESTARTing..."
  countdown "$timeout" &
  check
  # closing # TODO:
  exiting
}

suspend() {
  cya=(systemctl suspend)
  message="SUSPENding..."
  countdown "$timeout" &
  check
  exiting
}

logout() {
  cya=(systemctl suspend)
  message="⌛ LOGing-OFF..."
  countdown "$timeout" &
  check
  exiting
}

lock() {
  # Colors
  bg='1e1e2e' fg='d9e0ee' red='f38ba8' blue='89b4fa' magenta='cba6f7' cyan='89dceb' alpha='00000000'
  # bgl='313244' green='a6e3a1' yellow='f9e2af'
  
  swaylock -fFS \
    --ignore-empty-password \
    --show-failed-attempts \
    --hide-keyboard-layout \
    --indicator-caps-lock \
    --color ${bg}E6 \
    --font 'IosevkaLyteTerm' --font-size 70 \
    --key-hl-color ${magenta} \
    --caps-lock-key-hl-color ${blue} \
    --bs-hl-color ${red} \
    --caps-lock-bs-hl-color ${red} \
    --indicator-radius 200 \
    --indicator-thickness 20 \
    --inside-color ${alpha} \
    --inside-clear-color ${alpha} \
    --inside-caps-lock-color ${alpha} \
    --inside-ver-color ${red} \
    --inside-wrong-color ${magenta} \
    --layout-bg-color ${cyan} \
    --layout-border-color ${cyan} \
    --layout-text-color ${bg} \
    --line-color ${bg} \
    --line-clear-color ${red} \
    --line-caps-lock-color ${bg} \
    --line-ver-color ${bg} \
    --line-wrong-color ${bg} \
    --ring-color ${red} \
    --ring-clear-color ${bg} \
    --ring-caps-lock-color ${blue} \
    --ring-ver-color ${red} \
    --ring-wrong-color ${magenta} \
    --separator-color ${bg} \
    --text-color ${fg} \
    --text-clear-color ${fg} \
    --text-caps-lock-color ${fg} \
    --text-ver-color ${bg} \
    --text-wrong-color ${bg} \
    --timestr "%I:%M %p" \
    --datestr "%d / %m / %y" \
    --fade-in "0.2" \
    --effect-blur "7x3" \
    --effect-greyscale \
    --clock --indicator
  hyprctl dispatch dpms off 
}


# Execute functions accordingly
if [[ "$1" == "--test" ]]; then
  test
elif [[ "$1" == "--test" ]]; then
  test
elif [[ "$1" == "--shutdown" ]]; then
  shutdown
elif [[ "$1" == "--restart" ]]; then
  restart
elif [[ "$1" == "--suspend" ]]; then
  suspend
elif [[ "$1" == "--logout" ]]; then
  logout
elif [[ "$1" == "--lock" ]]; then
  lock
fi

# TODO: 
  # alternative icons for notify-send:
    # icon="/usr/share/icons/Adwaita/512x512/emblems/emblem-unreadable.png"
    # icon="/usr/share/icons/candy-icons/apps/scalable/zen-icon.svg"
    # icon="/usr/share/icons/BeautyLine/preferences/scalable/preferences-system-login.svg"
  # cancel button instead of "escape" key?...
    # -A cancel \   

