#!/usr/bin/env bash

# nosvagor
# https://raw.githubusercontent.com/nosvagor/dotfiles/main/bin/change-bg

DISPLAY="DP-3"
VID_PATH="$HOME/Videos/Hidamari"

background_choice=""
if [[ $# -eq 0 ]]; then
    background_choice="default"
else
    background_choice="$1"
fi

gravity () {
    mpvpaper -o "--loop --brightness=6 --contrast=9 --saturation=-16 --hue=-24 --mute=yes --video-unscaled=yes" $DISPLAY "$VID_PATH/gravity.mp4" & disown
}

AlternateRealities () {
    mpvpaper -o "--loop --brightness=-3 --contrast=10 --saturation=-42 --hue=69" $DISPLAY "$VID_PATH/AlternateRealities.mp4" & disown
}

blackhole () {
    mpvpaper -o "--loop --brightness=3  --contrast=6  --saturation=-50  --hue=-8 --gamma=-20" $DISPLAY "$VID_PATH/blackhole.webm" & disown
}


case "$background_choice" in
    "default" )
        ps -ef | rg "record|blackhole" | rg -v rg | awk '{print $2}' | xargs kill
        exit 0
    ;;
    "code")
        gravity & disown
        sleep 2
        ps -ef | rg "mpvpaper" | rg -v rg | awk '{print $2}' | head -n -1 | xargs kill
    ;;
    "music")
        record & disown
        ps -ef | rg "blackhole" | rg -v rg | awk '{print $2}' | xargs kill
    ;;
    "lock")
        blackhole & disown
        ps -ef | rg "record" | rg -v rg | awk '{print $2}' | xargs kill
    ;;
    *)
        echo "invalid choice; choices: code | music | lock"
        exit 1
    ;;
esac

exit 0

mpvpaper; mpvpaper -o "--loop-file=yes --mute=yes --video-unscaled=yes" /home/n30/Videos/Hidamari/2017-11-18\ 03-50-39.mp4
mpvpaper DP-3 -o "--loop-file=yes --mute=yes --video-unscaled=no" /run/media/n30/nvme_chivos/SteamLibrary/steamapps/workshop/content/431960/2523183859/AlternateRealities.mp4