#!/bin/bash

scriptsDir="$HOME"/.dotfiles/bin
wallsDir=$HOME/Videos/Hidamari

# Kill already running processes
_ps=(mpvpaper mako dunst swaync swaybg swayidle waybar mpd xdg-desktop-portal-hyprland xdg-desktop-portal xfce-polkit)
for _prs in "${_ps[@]}"; do
  if [[ $(pidof "${_prs}") ]]; then
    killall -9 "${_prs}"
  fi
done


# daemons
/usr/bin/numlockx on &
exec mpd &
xdg-user-dirs &
foot --server &

# video wallpaper
bash "$scriptsDir"/videowallpaper-change code &
# ${SCRIPTSDIR}/wall $HOME/.config/hypr/wallpapers/dreams.png &   #static wallpaper

#!/bin/bash
# Environment Variables
# https://wiki.hyprland.org/Configuring/Environment-variables/

# Toolkit Backend Variables
    export GDK_BACKEND=wayland,x11 #- GTK: Use wayland if available, fall back to x11 if not.
    # export QT_QPA_PLATFORM="wayland;xcb" #- QT: Use wayland if available, fall back to x11 if not.
    export SDL_VIDEODRIVER=wayland #- Run SDL2 applications on Wayland. Remove or set to x11 if games that provide older versions of SDL cause compatibility issues
    export CLUTTER_BACKEND=wayland #- Clutter package already has wayland enabled, this variable will force Clutter applications to try and use the Wayland backend

# XDG Specifications
# XDG specific environment variables are often detected through portals and applications that may set those for you, however it is not a bad idea to set them explicitly.
    export XDG_CURRENT_DESKTOP=Hyprland
    export XDG_SESSION_TYPE=wayland
    export XDG_SESSION_DESKTOP=Hyprland
    
# QT Variables
    export QT_AUTO_SCREEN_SCALE_FACTOR=1 #- (From the QT documentation) enables automatic scaling, based on the monitor’s pixel density
    export QT_QPA_PLATFORM="wayland;xcb" #- Tell QT applications to use the Wayland backend, and fall back to x11 if Wayland is unavailable
    export QT_WAYLAND_DISABLE_WINDOWDECORATION=1 #- Disables window decorations on QT applications
    export QT_QPA_PLATFORMTHEME=qt5ct #- Tells QT based applications to pick your theme from qt5ct, use with Kvantum.

# Theming Related Variables
    export XCURSOR_SIZE=32

# for flameshot:
    # export SDL_VIDEODRIVER=wayland
    export _JAVA_AWT_WM_NONREPARENTING=1

# https://github.com/nosvagor/dotfiles/blob/main/bin/hyprwrap   #adendum, clean dots tho
    export SDL_VIDEODRIVER=wayland
    export GDK_BACKEND="wayland,x11"
    export CLUTTER_BACKEND=wayland

# TODO: nvidia? test!
# https://www.reddit.com/r/hyprland/comments/10ww8y7/what_are_the_best_desktopwrappersconfigs_to/
    # export WLR_NO_HARDWARE_CURSORS=1

input {
    # http://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#switchable-keyboard-layouts
    kb_layout=latam         #because mexican 🇲🇽
    numlock_by_default=true
    follow_mouse=1
    touchpad {
        natural_scroll=no
    }
}

misc {
disable_hyprland_logo = true
disable_splash_rendering = true
mouse_move_enables_dpms = true
no_vfr = false # what does this do? o_o
no_direct_scanout = true #for fullscreen games
enable_swallow = true
swallow_regex = ^()$
}

general {
    sensitivity=1.0 # for mouse cursor
#     main_mod=SUPER
    gaps_in=5
    gaps_out=15
    border_size=8
    col.active_border=rgba(cba6f7ff) rgba(89b4faff) rgba(94e2d5ff) 10deg
    col.inactive_border=0xff45475a
    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)
    layout = dwindle        #TODO: change for master? 🤔
}

decoration {
    dim_inactive = 0
    rounding = 16
    multisample_edges = true

    blur_new_optimizations = true
    drop_shadow = true
    shadow_range=100
    shadow_render_power=5
    col.shadow= 0x33000000
    col.shadow_inactive=0x22000000
    rounding=15
    blur=1
    blurls = rofi
    blurls = wofi
    blur_size=5 # minimum 1
    blur_passes=1 # minimum 1, more passes = more resource intensive.
        # Your blur "amount" is blur_size * blur_passes, but high blur_size (over around 5-ish) will produce artifacts.
    # if you want heavy blur, you need to up the blur_passes.
    # the more passes, the more you can up the blur_size without noticing artifacts.
}

animations {
    enabled=1
    # bezier=overshot,0.05,0.9,0.1,1.1
    bezier=overshot,0.13,0.99,0.29,1.1
    animation=windows,1,4,overshot,slide
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,6,overshot,slidevert
}

dwindle {
    pseudotile=1 # enable pseudotiling on dwindle
    force_split=0
    col.group_border=0xff89dceb
    col.group_border_active=0xfff9e2af
    preserve_split = true       # https://wiki.hyprland.org/Configuring/Dwindle-Layout/

}

master {

}

gestures {
    workspace_swipe=yes
    workspace_swipe_fingers=4
}
