#!/bin/bash

# by neomikr0n

count() {
  timer -l "$1" | lolcat -a -d 1 -s 999 -t
}

glava() {
  glava
}

openbrowser() {
  # continuously check if the internet is available and open browser once it is
  while ! ping -c 1 google.com &> /dev/null
  do
      notify-send -e "I'm booting so fast!!! Internet is not available yet. Trying again in 5 seconds..."
      sleep 5
  done
  notify-send -e "Internet is available. Opening Browser :)"
  hyprctl dispatch workspace 2
  hyprctl dispatch exec [workspace 2] firedragon
}

heroiclauncher() {
  pkill heroic &
  heroic &
  pkill heroic &
  hyprctl dispatch exec [workspace 5 silent] heroic
}

gamescope3440() {
  pkill heroic
  gamescope -w 3440 -h 1440 -f -- heroic
}

gamescope2560() {
  pkill heroic
  gamescope -W 2560 -h 1080 -w 3440 -h 1440 -f -- heroic
}

# main
if [[ "$1" == "--count" ]]; then
  count "$2"
elif [[ "$1" == "--glava" ]]; then
  glava
elif [[ "$1" == "--openbrowser" ]]; then
  openbrowser
elif [[ "$1" == "--heroic" ]]; then
  heroiclauncher
elif [[ "$1" == "--gamescope3440" ]]; then
  gamescope3440
elif [[ "$1" == "--gamescope2560" ]]; then
  gamescope3440
else
  notify_user
fi