#!/bin/bash

# by neomikr0n

count() {
timer -l 88 | lolcat -a -d 1 -s 999 -t & disown
}


# main
if [[ "$1" == "--count" ]]; then
  count

elif [[ "$1" == "--notify" ]]; then
  notify_user
else
  notify_user
fi