#!/bin/bash

# by neomikr0n

count() {
timer -l "$1" | lolcat -a -d 1 -s 999 -t & disown
}


# main
if [[ "$1" == "--count" ]]; then
  count "$2"

elif [[ "$1" == "--notify" ]]; then
  notify_user
else
  notify_user
fi