#!/bin/bash

iDIR="$HOME/.config/dunst/icons"

# shutdown
shutdown() {
  
  # notify-send -h string:x-canonical-private-synchronous:sys-notify -u "$(get_urgency)" -i "$(get_icon)" -h  int:value:$(get_volume) "Volume : $(get_volume)%"
}

# Increase Volume
inc_volume() {
  pactl set-sink-volume @DEFAULT_SINK@ +5% && notify_user   
# pamixer -i 5 && notify_user     # an alternative to pactl, doesn't go beyond 100% tho
}

# Decrease Volume
dec_volume() {
  pactl set-sink-volume @DEFAULT_SINK@ -5% && notify_user   # an alternave is using pactl instead
  # pamixer -d 5 && notify_user   # an alternative to pactl, doesn't go beyond 100% tho
}

# Toggle Mute
toggle_mute() {
  if [ "$(pamixer --get-mute)" == "false" ]; then
    pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Volume Switched OFF"
  elif [ "$(pamixer --get-mute)" == "true" ]; then
    pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume Switched ON"
  fi
}

# Toggle Mic
toggle_mic() {
  if [ "$(pamixer --source 66 --get-mute)" == "false" ]; then
    pamixer -m --source 66 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
  elif [ "$(pamixer --source 66 --get-mute)" == "true" ]; then
    pamixer -u --source 66 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
  fi
}

up() {
pamixer -i 5 && notify_user
}

down() {
pamixer -d 5 && notify_user
}


# Execute accordingly
if [[ "$1" == "--get" ]]; then
  get_volume
elif [[ "$1" == "--inc" ]]; then
  inc_volume
elif [[ "$1" == "--dec" ]]; then
  dec_volume
elif [[ "$1" == "--toggle" ]]; then
  toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
  toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
  get_icon
elif [[ "$1" == "--up" ]]; then
  up
elif [[ "$1" == "--down" ]]; then
  down
elif [[ "$1" == "--notify" ]]; then
  notify_user
else
  get_volume & notify_user
fi


# iamverysimp1e's script:
# https://github.com/iamverysimp1e/dots/blob/main/configs/hypr/scripts/volume
# 
# up() {
# pamixer -i 5
# volume=$(pamixer --get-volume)
# [ $volume -lt 100 ] && volume=`expr $volume`  
# dunstify -a "VOLUME" "Volume : $volume%" -h int:value:"$volume" -i audio-volume-high-symbolic -r 2593 -u normal
# canberra-gtk-play -i audio-volume-change -d "changevolume"
# }

# down() {
# pamixer -d 5
# volume=$(pamixer --get-volume)
# [$volume -gt 0 ] && volume=`expr $volume`  
# dunstify -a "VOLUME" "Volume : $volume%" -h int:value:"$volume" -i audio-volume-low-symbolic -r 2593 -u normal
# canberra-gtk-play -i audio-volume-change -d "changevolume"
# }


# mute() {
# muted="$(pamixer --get-mute)"
# if $muted; then
#   pamixer -u
#   dunstify -a "VOLUME" "UNMUTED" -i audio-volume-high-symbolic -r 2593 -u normal
# else 
#   pamixer -m
#   dunstify -a "VOLUME" "MUTED" -i audio-volume-muted-symbolic -r 2593 -u normal
# fi
# }