#!/bin/bash

iDIR="$HOME/.config/dunst/icons"

# Get Volume
get_volume() {
  volume=$(pamixer --get-volume)
  echo "$volume"
}

# Get icons
get_icon() {
  current=$(get_volume)
  if [[ "$current" -eq "0" ]]; then
    echo "$iDIR/volume-mute.png"
  elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
    echo "$iDIR/volume-low.png"
  elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
    echo "$iDIR/volume-mid.png"
  elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
    echo "$iDIR/volume-high.png"
  elif [[ ("$current" -ge "100") && ("$current" -le "200") ]]; then
    echo "$iDIR/volume-veryhigh.avif"
  fi
}

# Get urgency
get_urgency() {
  current=$(get_volume)
  if [[ "$current" -eq "0" ]]; then
    echo "low"
  elif [[ ("$current" -ge "0") && ("$current" -le "100") ]]; then
    echo "low"
  elif [[ ("$current" -ge "100") && ("$current" -le "130") ]]; then
    echo "normal"  
    elif [[ ("$current" -ge "130") && ("$current" -le "200") ]]; then
    echo "critical"
  fi
}

# Notify
notify_user() {
  notify-send -h string:x-canonical-private-synchronous:sys-notify -u "$(get_urgency)" -i "$(get_icon)" -h  int:value:$(get_volume) "Volume : $(get_volume)"
}

# Increase Volume
inc_volume() {
  pactl set-sink-volume @DEFAULT_SINK@ +5% && notify_user
# pamixer -i 5 && notify_user   # an alternave is using pamixer instead
}

# Decrease Volume
dec_volume() {
  pactl set-sink-volume @DEFAULT_SINK@ -5% && notify_user
#   pamixer -d 5 && notify_user   # an alternave is using pamixer instead
}

# Toggle Mute
toggle_mute() {
  if [ "$(pamixer --get-mute)" == "false" ]; then
    pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Volume Switched OFF"
  elif [ "$(pamixer --get-mute)" == "true" ]; then
    pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume Switched ON"
  fi
}

# Toggle Mic
toggle_mic() {
  if [ "$(pamixer --source 66 --get-mute)" == "false" ]; then
    pamixer -m --source 66 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
  elif [ "$(pamixer --source 66 --get-mute)" == "true" ]; then
    pamixer -u --source 66 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
  fi
}

# iamverysimp1e's script:
# https://github.com/iamverysimp1e/dots/blob/main/configs/hypr/scripts/volume
# 
up() {
pamixer -i 5
volume=$(pamixer --get-volume)
[ $volume -lt 100 ] && volume=`expr $volume`  
dunstify -a "VOLUME" "Volume : $volume%" -h int:value:"$volume" -i audio-volume-high-symbolic -r 2593 -u normal
canberra-gtk-play -i audio-volume-change -d "changevolume"
}

down() {
pamixer -d 5
volume=$(pamixer --get-volume)
[$volume -gt 0 ] && volume=`expr $volume`  
dunstify -a "VOLUME" "Volume : $volume%" -h int:value:"$volume" -i audio-volume-low-symbolic -r 2593 -u normal
canberra-gtk-play -i audio-volume-change -d "changevolume"
}


# Execute accordingly
if [[ "$1" == "--get" ]]; then
  get_volume
elif [[ "$1" == "--inc" ]]; then
  inc_volume
elif [[ "$1" == "--dec" ]]; then
  dec_volume
elif [[ "$1" == "--toggle" ]]; then
  toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
  toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
  get_icon
elif [[ "$1" == "--up" ]]; then
  up
elif [[ "$1" == "--down" ]]; then
  down
else
  get_volume
fi





# mute() {
# muted="$(pamixer --get-mute)"
# if $muted; then
#   pamixer -u
#   dunstify -a "VOLUME" "UNMUTED" -i audio-volume-high-symbolic -r 2593 -u normal
# else 
#   pamixer -m
#   dunstify -a "VOLUME" "MUTED" -i audio-volume-muted-symbolic -r 2593 -u normal
# fi
# }