#!/usr/bin/env bash
CONFIG="$HOME/.config/swaync/config"
STYLE="$HOME/.config/swaync/style.css"
# CONFIG="$HOME/.config/hypr/component/waybar/config"
# STYLE="$HOME/.config/hypr/component/waybar/style.css"

killall -q swaync  & sleep 0.5 
if [[ ! $(pidof waybar) ]]; then
  waybar -c ${CONFIG} -s ${STYLE}
fi

if [[ ! $(pidof swaync) ]]; then
  swaync
fi






# NOTIFICATIONS (mako)
# CONFIG="$HOME/.config/mako/config"

# if [[ ! $(pidof mako) ]]; then
#   mako -c ${CONFIG}
# fi
