#!/bin/bash

#  @mkroman
# mkroman
# https://gist.github.com/mkroman/1326550

name="dotfiles_$(date +%d-%m-%y-%X)"
archive="/tmp/${name}.tar.xz"
destination="/tmp/${name}"

echo "-> Commencing backup"
rsync -a --filter="merge ${HOME}/.dotfiles" --exclude "*" ${HOME}/ ${destination}

if [[ -d ${destination} ]]; then
	echo "--> Compressing files"
	tar --lzma -cf ${archive} -C /tmp ${name}

	if [ ! -e ${archive} ]; then
		echo "!> Failed to compress archive."
		exit 1
	else
		echo "--> Encrypting archive"
		gpg2 --encrypt --sign --recipient 0xCFD3219C ${archive}

		original_size=$(du -sh ${destination} | cut -f1)
		archive_size=$(du -sh ${archive}.gpg | cut -f1)

		rm -f ${archive}
		rm -rf ${destination}

		echo "--> Uploading a total of ${archive_size} (${original_size})"
		scp -q ${archive}.gpg namus.nodes.cycle.io:~/backups/
		echo "-> Backup complete"

		rm ${archive}.gpg
		exit 0
	fi
fi
