#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
# _ps=(waybar mako)
# for _prs in "${_ps[@]}"; do
#   if [[ $(pidof ${_prs}) ]]; then
#     killall -9 ${_prs}
#   fi
# done

# Apply themes
# ${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# daemons
/usr/bin/numlockx on &

# wallpaper & effects
${SCRIPTSDIR}/tools/dynamic &
${SCRIPTSDIR}/wall $HOME/.config/hypr/wallpapers/dreams.png & # for the transitions of swww_fork
${SCRIPTSDIR}/rgb &
