#!/bin/bash
# STATUSBAR (waybar)
CONFIG="$HOME/.config/hypr/component/waybar/config"
STYLE="$HOME/.config/hypr/component/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
  waybar --log-level error --config ${CONFIG} --style ${STYLE}
fi

# if [[ ! $(pidof waybar) ]]; then
#   waybar --log-level error --config ${CONFIG} --style ${STYLE}
# fi

# messy alternative, one line tho:
# killall -q waybar & sleep 0.5 && waybar -c $HOME/.config/hypr/component/waybar/config -s $HOME/.config/hypr/component/waybar/style.css &

